version: '3'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - backend

    koj:
        image: ubuntu:editor
        volumes:
            - .:/Koreatech-OJ
        ports:
            - "8000:8000"
        networks:
            - backend
        environment:
            - PYTHONUNBUFFERED=1
        command:
            - bash
            - -c
            - |
              nohup python3 manage.py celery &
              python3 manage.py runserver 0.0.0.0:8000


networks:
    backend:
        
